export const API_URL = 'https://api.data.gov.sg/v1/transport/traffic-images';

export const REFRESH_INTERVALS = {
  FAST: 60,   // 1 minute
  NORMAL: 300, // 5 minutes
  SLOW: 600,   // 10 minutes
};

export const AVAILABLE_MODELS = [
  { id: 'gemma-3-27b-it', name: 'Gemma 3 27B IT (Sample Default)' },
];

export const DEFAULT_PREFERENCES = {
  refreshInterval: REFRESH_INTERVALS.NORMAL,
  autoRefresh: true,
  showHeatmap: false,
  theme: 'light' as const,
  watchlist: [] as string[],
  modelId: 'gemma-3-27b-it',
  apiKey: '',
};

// Singapore Bounds for initialization
export const SG_LAT = 1.3521;
export const SG_LNG = 103.8198;
export const DEFAULT_ZOOM = 11;

// Heuristic Road Configuration
export const CORRIDOR_CONFIG = [
  { id: 'PIE', name: 'PIE (Pan Island Expressway)', pattern: /PIE/ },
  { id: 'AYE', name: 'AYE (Ayer Rajah Expressway)', pattern: /AYE/ },
  { id: 'CTE', name: 'CTE (Central Expressway)', pattern: /CTE/ },
  { id: 'ECP', name: 'ECP (East Coast Parkway)', pattern: /ECP/ },
  { id: 'TPE', name: 'TPE (Tampines Expressway)', pattern: /TPE/ },
  { id: 'KPE', name: 'KPE (Kallang-Paya Lebar)', pattern: /KPE/ },
  { id: 'SLE', name: 'SLE (Seletar Expressway)', pattern: /SLE/ },
  { id: 'BKE', name: 'BKE (Bukit Timah Expressway)', pattern: /BKE/ },
  { id: 'KJE', name: 'KJE (Kranji Expressway)', pattern: /KJE/ },
  { id: 'WOODLANDS', name: 'Causeway / Woodlands', pattern: /Woodlands/ },
  { id: 'TUAS', name: 'Tuas Checkpoint', pattern: /Tuas/ },
];

export const ROAD_NAMES: Record<string, string> = {
  '1001': 'KJE (Choa Chu Kang)',
  '1002': 'KJE (Tengah)',
  '1003': 'KJE (Murai)',
  '1004': 'KJE (Sungei Tengah)',
  '1005': 'KJE (Brickland)',
  '1006': 'KJE (Gombak)',
  '1111': 'TPE (Punggol)',
  '1112': 'TPE (Sengkang)',
  '1113': 'TPE (Tampines)',
  '1501': 'AYE (Jurong)',
  '1502': 'AYE (Clementi)',
  '1503': 'AYE (Lower Delta)',
  '1504': 'AYE (Alexandra)',
  '1505': 'AYE (Keppel)',
  '1701': 'PIE (Tuas)',
  '1702': 'ECP (City)',
  '1703': 'PIE (Adam)',
  '1704': 'CTE (City)',
  '1705': 'PIE (Mount Pleasant)',
  '1706': 'PIE (Kallang)',
  '1707': 'PIE (Paya Lebar)',
  '1708': 'PIE (Bedok)',
  '1709': 'KPE (TPE)',
  '1710': 'KPE (ECP)',
  '1711': 'CTE (Ang Mo Kio)',
  '2701': 'Woodlands Checkpoint',
  '2702': 'Tuas Checkpoint',
  '2703': 'BKE (Chantek)',
  '2704': 'BKE (Woodlands)',
  '2705': 'BKE (Dairy Farm)',
  '2706': 'SLE (Lentor)',
  '2707': 'SLE (Upper Thomson)',
  '2708': 'SLE (Mandai)',
  '3702': 'ECP (Marine Parade)',
  '3704': 'ECP (Tanjong Katong)',
  '3705': 'ECP (Bedok South)',
  '3793': 'MCE (Marina Coastal)',
  '3795': 'MCE (Fort Rd)',
  '3796': 'MCE (Tunnel)',
  '3797': 'MCE (Marina Blvd)',
  '3798': 'MCE (Maxwell)',
  '4701': 'PIE (Jurong West)',
  '4702': 'PIE (Toh Guan)',
  '4703': 'PIE (Bukit Batok)',
  '4704': 'PIE (Bukit Timah)',
  '4705': 'PIE (Eng Neo)',
  '4706': 'PIE (Eunos)',
  '4707': 'PIE (Changi)',
  '4708': 'PIE (Simei)',
  '4709': 'PIE (Tampines)',
  '4710': 'PIE (Pasir Ris)',
  '4712': 'PIE (Nanyang)',
  '4713': 'PIE (Jln Bahar)',
  '4714': 'PIE (Upper Jurong)',
  '4716': 'PIE (Clementi Ave 6)',
  '5794': 'CTE (Moulmein)',
  '5795': 'CTE (Braddell)',
  '5797': 'CTE (Bukit Merah)',
  '5798': 'CTE (Chin Swee)',
  '5799': 'CTE (Outram)',
  '6701': 'BKE (Mandai)',
  '6703': 'BKE (Dairy Farm)',
  '6704': 'BKE (Chestnut)',
  '6705': 'BKE (Hillview)',
  '6706': 'BKE (Bukit Panjang)',
  '6708': 'SLE (Yio Chu Kang)',
  '6710': 'SLE (BKE)',
  '6711': 'SLE (Mandai Lake)',
  '6712': 'SLE (Marsiling)',
  '6713': 'SLE (Woodlands Ave 2)',
  '6714': 'SLE (Ulu Sembawang)',
  '6715': 'SLE (Upper Seletar)',
  '6716': 'SLE (Lentor Ave)',
  '7791': 'TPE (Punggol Road)',
  '7793': 'TPE (Jalan Kayu)',
  '7794': 'TPE (Seletar)',
  '7795': 'TPE (Tampines Ave 10)',
  '7796': 'TPE (Pasir Ris Dr 12)',
  '7797': 'TPE (Loyang)',
  '7798': 'TPE (Upper Changi)',
  '8701': 'KPE (Defu)',
  '8702': 'KPE (Kallang Bahru)',
  '8704': 'KPE (Airport Rd)',
  '8706': 'KPE (Tampines Rd)',
  '9701': 'Lornie Highway',
  '9702': 'Lornie Highway (Adam)',
  '9703': 'Lornie Highway (Farrer)',
  '9704': 'Lornie Highway (Kheam Hock)',
  '9705': 'Lornie Highway (Sime)',
  '9706': 'Lornie Highway (MacRitchie)',
};
